#!/usr/bin/env bash
# install.sh — link dotfiles from this repo into a target home directory.
#
# Usage: install.sh [OPTIONS]
#   --dotfiles=PATH   Source repo path (default: directory containing this script)
#   --target=PATH     Install destination (default: $HOME)
#   --backup=PATH     Backup directory (default: <target>/.dotfiles-backup/<timestamp>)
#   --dry-run         Show what would happen, change nothing
#   --no-tmux-plugins Skip cloning catppuccin tmux
#   -h, --help        Show usage
#
# The script is idempotent: re-running on an installed machine reports "ok: already linked"
# for each path. Every change is preceded by a snapshot to the backup dir, and an
# auto-generated restore.sh is written there for one-command rollback.

set -euo pipefail

# --- parse args ---
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOTFILES="$SCRIPT_DIR"
TARGET="$HOME"
BACKUP=""
DRY_RUN=0
SKIP_TMUX_PLUGINS=0

usage() { sed -n '3,13p' "$0" | sed 's/^# \{0,1\}//'; }

for arg in "$@"; do
  case "$arg" in
    --dotfiles=*)      DOTFILES="${arg#*=}" ;;
    --target=*)        TARGET="${arg#*=}" ;;
    --backup=*)        BACKUP="${arg#*=}" ;;
    --dry-run)         DRY_RUN=1 ;;
    --no-tmux-plugins) SKIP_TMUX_PLUGINS=1 ;;
    -h|--help)         usage; exit 0 ;;
    *) echo "Unknown arg: $arg" >&2; usage >&2; exit 1 ;;
  esac
done
: "${BACKUP:=$TARGET/.dotfiles-backup/$(date +%Y%m%d-%H%M%S)}"

# Resolve to absolute paths so symlinks and restore.sh work regardless of cwd.
DOTFILES="$(cd "$DOTFILES" && pwd)"
mkdir -p "$TARGET" && TARGET="$(cd "$TARGET" && pwd)"

# --- helpers ---
run() { if (( DRY_RUN )); then echo "DRY: $*"; else "$@"; fi; }

MANIFEST=""
log() {
  echo "$@"
  if [[ -n "$MANIFEST" ]] && (( ! DRY_RUN )); then
    echo "$@" >> "$MANIFEST"
  fi
}

# --- paths to manage (relative to $TARGET / $DOTFILES) ---
PATHS=(
  .zshrc
  .zprofile
  .bash_aliases
  .ideavimrc
  .config/starship.toml
  .config/tmux/tmux.conf
  .config/nvim
)

echo "dotfiles: $DOTFILES"
echo "target:   $TARGET"
echo "backup:   $BACKUP"
(( DRY_RUN )) && echo "mode:     DRY RUN (no changes)"
echo

# --- pre-flight backup pass ---
run mkdir -p "$BACKUP"
if (( ! DRY_RUN )); then
  MANIFEST="$BACKUP/manifest.txt"
  : > "$MANIFEST"
  log "# install.sh manifest — $(date)"
  log "# dotfiles=$DOTFILES target=$TARGET"
fi

for p in "${PATHS[@]}"; do
  dest="$TARGET/$p"
  if [[ -e "$dest" || -L "$dest" ]]; then
    # Skip backup if the destination is already the symlink we'd create — nothing to lose.
    if [[ -L "$dest" && "$(readlink "$dest")" == "$DOTFILES/$p" ]]; then
      continue
    fi
    run mkdir -p "$BACKUP/$(dirname "$p")"
    # -a preserves attrs, -L dereferences symlinks so we capture real content.
    # -H would only deref command-line args; -L is what we want for nested symlinks too.
    run cp -aL "$dest" "$BACKUP/$p"
    log "backup: $dest -> $BACKUP/$p"
  fi
done

# --- linking pass ---
for p in "${PATHS[@]}"; do
  src="$DOTFILES/$p"
  dest="$TARGET/$p"
  if [[ ! -e "$src" ]]; then
    log "skip (missing in repo): $p"
    continue
  fi
  if [[ -L "$dest" && "$(readlink "$dest")" == "$src" ]]; then
    log "ok: $dest already linked"
    continue
  fi
  run mkdir -p "$(dirname "$dest")"
  if [[ -e "$dest" || -L "$dest" ]]; then
    run rm -rf "$dest"
  fi
  run ln -s "$src" "$dest"
  log "link: $dest -> $src"
done

# --- catppuccin tmux ---
CATPPUCCIN_CLONED=0
if (( ! SKIP_TMUX_PLUGINS )); then
  CATPPUCCIN="$TARGET/.config/tmux/plugins/catppuccin/tmux"
  if [[ ! -d "$CATPPUCCIN" ]]; then
    run mkdir -p "$(dirname "$CATPPUCCIN")"
    run git clone -b v2.1.3 https://github.com/catppuccin/tmux.git "$CATPPUCCIN"
    log "clone: $CATPPUCCIN"
    CATPPUCCIN_CLONED=1
  else
    log "ok: catppuccin tmux already present at $CATPPUCCIN"
  fi
fi

# --- generate restore.sh ---
if (( ! DRY_RUN )); then
  cat > "$BACKUP/restore.sh" <<'RESTORE'
#!/usr/bin/env bash
# Auto-generated by install.sh. Reverses the install for the run that created this dir.
set -euo pipefail
BACKUP="$(cd "$(dirname "$0")" && pwd)"
TARGET="__TARGET__"
DOTFILES="__DOTFILES__"
CATPPUCCIN_CLONED=__CATPPUCCIN_CLONED__
PATHS=(__PATHS__)

echo "Restoring from: $BACKUP"
echo "Target:         $TARGET"
echo

for p in "${PATHS[@]}"; do
  dest="$TARGET/$p"
  # Only remove the symlink if it still points where we set it — never touch user-modified state.
  if [[ -L "$dest" && "$(readlink "$dest")" == "$DOTFILES/$p" ]]; then
    rm "$dest"
    echo "unlink: $dest"
  fi
  if [[ -e "$BACKUP/$p" ]]; then
    mkdir -p "$(dirname "$dest")"
    # If something else is sitting at $dest (e.g. user re-created the file), don't clobber.
    if [[ -e "$dest" || -L "$dest" ]]; then
      echo "warn: $dest exists, leaving in place; backup at $BACKUP/$p" >&2
      continue
    fi
    cp -a "$BACKUP/$p" "$dest"
    echo "restore: $dest"
  fi
done

if (( CATPPUCCIN_CLONED )); then
  CATPPUCCIN="$TARGET/.config/tmux/plugins/catppuccin/tmux"
  if [[ -d "$CATPPUCCIN" ]]; then
    rm -rf "$CATPPUCCIN"
    rmdir "$(dirname "$CATPPUCCIN")" 2>/dev/null || true
    echo "remove: $CATPPUCCIN (cloned by install.sh)"
  fi
fi

echo
echo "Done. Backup directory left in place: $BACKUP"
RESTORE
  # Substitute placeholders with actual values.
  sed -i.bak \
    -e "s|__TARGET__|$TARGET|" \
    -e "s|__DOTFILES__|$DOTFILES|" \
    -e "s|__CATPPUCCIN_CLONED__|$CATPPUCCIN_CLONED|" \
    -e "s|__PATHS__|${PATHS[*]}|" \
    "$BACKUP/restore.sh"
  rm -f "$BACKUP/restore.sh.bak"
  chmod +x "$BACKUP/restore.sh"
fi

echo
if (( DRY_RUN )); then
  echo "✔ Dry run complete — nothing changed."
else
  echo "✔ Done."
  echo "  Backup:   $BACKUP"
  echo "  Rollback: $BACKUP/restore.sh"
fi
